### ISSUE TITLE
error

### ISSUE THREAD

**Issue by silverv** [OpenCyphal/yukon#279]
Traceback (most recent call last):
  File "/home/silver/yukon/venv/lib/python3.10/site-packages/pycyphal/util/_broadcast.py", line 46, in delegate
    r: typing.Union[R, Exception] = fn(*args, **kwargs)
  File "/home/silver/yukon/yukon/domain/avatar.py", line 199, in _on_trace
    handler(float(ts.monotonic), deserialized_object, tr.metadata.transfer_id)  # type: ignore
  File "/home/silver/yukon/yukon/domain/avatar.py", line 101, in _on_access_response
    register_name = self.access_requests_names_by_transfer_id[transfer_id]
KeyError: 0

**Comment by silverv** [comment]
is not critical
